# This is a basic workflow to help you get started with Actions

name: AlterarColunaBoardPM
on:
  issues:
    type: [edited]
jobs:
  automate-project-columns:
    if: column == "Open"
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
            project: Geral
            column: Pronta para Desenvolvimento
            repo-token: ${{ secrets.GITHUB_TOKEN }}
