# This is a basic workflow to help you get started with Actions

name: AlterarColunaBoardPM

# Controls when the workflow will run
on:
  issues:
    type: [edited]
    column: [Open]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel ---repo-token:
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
        - name: GitHub Project Automation+
          uses: alex-page/github-project-automation-plus@v0.8.3

          with:
            project: Geral
            column: Pronta para Desenvolvimento
            repo-token: ${{ secrets.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 }}
